### ISSUE TITLE
gcc error: CreateProcess: No such file or directory

### ISSUE THREAD

**Issue by eelsivart** [ColdHeat/iclass#1]
I am trying to compile and have followed the directions for installing mingw and when i run "make", i get this error:

gcc -W -Wno-write-strings -Wno-unused-function -O4 -DNDEBUG -Iopenssl/include -Iwincard/include -c -o iclassified.o iclassified.c
gcc.exe: error: CreatePRocess: No such file or directory
make: *** [iclassified.o] Error 1

**Comment by ColdHeat** [comment]
Perhaps rename that to `CreateProcess` ?

This isn't something I've run into before and I presume it's something specific to your environment.

**Comment by eelsivart** [comment]
It was a problem with mingw. I had it on Win XP and it wasn't working so I tried compiling it with mingw on linux and it worked... weird.

**Comment by ColdHeat** [comment]
Hmm unfortunately if it's in Linux you probably won't be able to read any cards b/c the drivers are for Windows XP. 

You should be able to get it working in XP though.

**Comment by eelsivart** [comment]
I was just using linux to compile the .exe. I moved it over to Win XP to do the actual reads/writes. Once I get my omnikey, I'll be able to test it out. thanks!
